# Flavor Tagging
set PARAM_TRACKPTMIN 0.75
set PARAM_TRACKIPMAX 3.0
set PARAM_TRACKSIGMIN 3.75
set PARAM_TRACKSNMIN 2
set PARAM_D0RES 0.020
set PARAM_DZRES 0.020

# Other Parameters
set PARAM_BZ 1.5

